module.exports = {
  name: 'Cognite JavaScript SDK',
  mode: 'file',
  module: 'umd',
  target: 'ES6',
  exclude: '**/__tests__/**',
  out: './docs/',
  theme: 'markdown',
  readme: 'none',
  // readme: 'https://github.com/cognitedata/cognitesdk-js/blob/v1/README.md',
  ignoreCompilerErrors: true,
  excludeNotExported: true,
  hideGenerator: true,
  excludePrivate: true,
  excludeProtected: true,
  includeDeclarations: true,
  excludeExternals: true,
};
